INSERT INTO `Place` (`id`, `description`) VALUES (0,"");
INSERT INTO `Place` (`id`, `description`) VALUES (47,"GAMBLING FACILITY/CASINO");
INSERT INTO `Place` (`id`, `description`) VALUES (60,"RAILROAD-CABOOSE");
INSERT INTO `Place` (`id`, `description`) VALUES (88,"HOUSING PROJECT");
INSERT INTO `Place` (`id`, `description`) VALUES (89,"RAILROAD PLACES-OTHER");
INSERT INTO `Place` (`id`, `description`) VALUES (90,"APARTMENT");
INSERT INTO `Place` (`id`, `description`) VALUES (91,"APARTMENT-STORAGE LOCKER");
INSERT INTO `Place` (`id`, `description`) VALUES (92,"ALLEY");
INSERT INTO `Place` (`id`, `description`) VALUES (93,"APARTMENT-COMMON AREA");
INSERT INTO `Place` (`id`, `description`) VALUES (94,"CONDOMINIUM");
INSERT INTO `Place` (`id`, `description`) VALUES (95,"AIRPORT");
INSERT INTO `Place` (`id`, `description`) VALUES (96,"PARKING LOT-APARTMENT");
INSERT INTO `Place` (`id`, `description`) VALUES (97,"SHELTERS(WOMEN/HOMELESS)");
INSERT INTO `Place` (`id`, `description`) VALUES (98,"BUS STOP");
INSERT INTO `Place` (`id`, `description`) VALUES (99,"SALVATION ARMY/GOOD WILL");
INSERT INTO `Place` (`id`, `description`) VALUES (100,"BANK");
INSERT INTO `Place` (`id`, `description`) VALUES (101,"BIKE RACK");
INSERT INTO `Place` (`id`, `description`) VALUES (102,"BARBER SHOP");
INSERT INTO `Place` (`id`, `description`) VALUES (103,"BAR OR TAVERN");
INSERT INTO `Place` (`id`, `description`) VALUES (104,"BOAT");
INSERT INTO `Place` (`id`, `description`) VALUES (107,"BOAT HOUSE");
INSERT INTO `Place` (`id`, `description`) VALUES (109,"BOWLING ALLEY");
INSERT INTO `Place` (`id`, `description`) VALUES (110,"BUILDING - OTHER");
INSERT INTO `Place` (`id`, `description`) VALUES (111,"OFFICE BUILDING");
INSERT INTO `Place` (`id`, `description`) VALUES (120,"BUS");
INSERT INTO `Place` (`id`, `description`) VALUES (130,"BUS GARAGE");
INSERT INTO `Place` (`id`, `description`) VALUES (131,"BUS TERMINAL");
INSERT INTO `Place` (`id`, `description`) VALUES (132,"BRIDGE");
INSERT INTO `Place` (`id`, `description`) VALUES (140,"BUSINESS - COMMERCIAL");
INSERT INTO `Place` (`id`, `description`) VALUES (144,"CAR WASH");
INSERT INTO `Place` (`id`, `description`) VALUES (145,"CEMETERY");
INSERT INTO `Place` (`id`, `description`) VALUES (146,"CHILDREN'S HOME");
INSERT INTO `Place` (`id`, `description`) VALUES (150,"CHAIN STORE");
INSERT INTO `Place` (`id`, `description`) VALUES (151,"CHURCH");
INSERT INTO `Place` (`id`, `description`) VALUES (152,"COAL MINE");
INSERT INTO `Place` (`id`, `description`) VALUES (160,"COIN OPERATED MACHINE");
INSERT INTO `Place` (`id`, `description`) VALUES (161,"CONV STORE-INDEPENDANT");
INSERT INTO `Place` (`id`, `description`) VALUES (162,"CONV STORE-CHAIN");
INSERT INTO `Place` (`id`, `description`) VALUES (168,"CURRENCY EXCHANGE");
INSERT INTO `Place` (`id`, `description`) VALUES (169,"COLLEGE GROUNDS OR BLDG");
INSERT INTO `Place` (`id`, `description`) VALUES (170,"COLLEGE RESIDENCE HALL");
INSERT INTO `Place` (`id`, `description`) VALUES (171,"CONSTRUCTION SITE");
INSERT INTO `Place` (`id`, `description`) VALUES (172,"CONSTRUCTION COMPANY");
INSERT INTO `Place` (`id`, `description`) VALUES (173,"DEPARTMENT STORE-INDEP.");
INSERT INTO `Place` (`id`, `description`) VALUES (174,"DEPARTMENT STORE-CHAIN");
INSERT INTO `Place` (`id`, `description`) VALUES (175,"CREDIT UNION");
INSERT INTO `Place` (`id`, `description`) VALUES (176,"DRIVEWAY-RESIDENTIAL");
INSERT INTO `Place` (`id`, `description`) VALUES (177,"DAY CARE CENTER");
INSERT INTO `Place` (`id`, `description`) VALUES (189,"DRUG REHAB HALFWAY HOUSE");
INSERT INTO `Place` (`id`, `description`) VALUES (190,"DRUG STORE-INDEPENDENT");
INSERT INTO `Place` (`id`, `description`) VALUES (191,"DRUG STORE-CHAIN");
INSERT INTO `Place` (`id`, `description`) VALUES (192,"DRY CLEANER");
INSERT INTO `Place` (`id`, `description`) VALUES (193,"FRATERNAL CLUBS");
INSERT INTO `Place` (`id`, `description`) VALUES (200,"LAND - VACANT");
INSERT INTO `Place` (`id`, `description`) VALUES (201,"FARM BUILDING");
INSERT INTO `Place` (`id`, `description`) VALUES (202,"FARM PASTURE");
INSERT INTO `Place` (`id`, `description`) VALUES (203,"FARM PEN OR CORRAL");
INSERT INTO `Place` (`id`, `description`) VALUES (204,"FARM LAND TILLED");
INSERT INTO `Place` (`id`, `description`) VALUES (206,"ATHLETIC CLUB");
INSERT INTO `Place` (`id`, `description`) VALUES (207,"HEALTH CENTER");
INSERT INTO `Place` (`id`, `description`) VALUES (208,"FRATERNITY HOUSE");
INSERT INTO `Place` (`id`, `description`) VALUES (209,"FACTORY OR MANUF. BLDG");
INSERT INTO `Place` (`id`, `description`) VALUES (210,"GARAGE - RESIDENTIAL");
INSERT INTO `Place` (`id`, `description`) VALUES (211,"FAIR GROUNDS");
INSERT INTO `Place` (`id`, `description`) VALUES (212,"FIRE STATION");
INSERT INTO `Place` (`id`, `description`) VALUES (213,"FARM IMPLMT&SUPPLY BUSINE");
INSERT INTO `Place` (`id`, `description`) VALUES (215,"GARAGE - AUTO REPAIRS");
INSERT INTO `Place` (`id`, `description`) VALUES (220,"GAS/AUTO SERVICE STATION");
INSERT INTO `Place` (`id`, `description`) VALUES (222,"GOLF COURSE");
INSERT INTO `Place` (`id`, `description`) VALUES (223,"GRAIN ELEVATOR");
INSERT INTO `Place` (`id`, `description`) VALUES (224,"GROCERY/FOOD STORE-INDEP.");
INSERT INTO `Place` (`id`, `description`) VALUES (225,"GROCERY/FOOD STORE-CHAIN");
INSERT INTO `Place` (`id`, `description`) VALUES (226,"INDUSTRIAL PARK");
INSERT INTO `Place` (`id`, `description`) VALUES (230,"GYM LOCKER(INCLUDES SCHL)");
INSERT INTO `Place` (`id`, `description`) VALUES (232,"MENTAL INSTITUTION");
INSERT INTO `Place` (`id`, `description`) VALUES (233,"HOSPITAL");
INSERT INTO `Place` (`id`, `description`) VALUES (236,"HARDWARE STORE-INDEPENDT.");
INSERT INTO `Place` (`id`, `description`) VALUES (237,"HARDWARE STORE - CHAIN");
INSERT INTO `Place` (`id`, `description`) VALUES (238,"HIGHWAY");
INSERT INTO `Place` (`id`, `description`) VALUES (239,"JEWELRY STORE");
INSERT INTO `Place` (`id`, `description`) VALUES (241,"JUNK YARD/SALVAGE YARD");
INSERT INTO `Place` (`id`, `description`) VALUES (242,"LAW ENFORCEMENT BUILDING");
INSERT INTO `Place` (`id`, `description`) VALUES (243,"LIQUOR STORE - INDEPENDT.");
INSERT INTO `Place` (`id`, `description`) VALUES (244,"LIQUOR STORE - CHAIN");
INSERT INTO `Place` (`id`, `description`) VALUES (245,"LIBRARY");
INSERT INTO `Place` (`id`, `description`) VALUES (246,"LUMBER YARD");
INSERT INTO `Place` (`id`, `description`) VALUES (247,"LAUNDROMAT");
INSERT INTO `Place` (`id`, `description`) VALUES (248,"LOCKER ROOM");
INSERT INTO `Place` (`id`, `description`) VALUES (249,"MAILBOX");
INSERT INTO `Place` (`id`, `description`) VALUES (250,"MEDICAL OFFICES");
INSERT INTO `Place` (`id`, `description`) VALUES (251,"MOBILE HOME - PERMANENT");
INSERT INTO `Place` (`id`, `description`) VALUES (252,"MOBILE HOME PARK");
INSERT INTO `Place` (`id`, `description`) VALUES (253,"VACATION/CAMPER TRAILER");
INSERT INTO `Place` (`id`, `description`) VALUES (254,"URGENT CARE CENTER");
INSERT INTO `Place` (`id`, `description`) VALUES (255,"VIDEO STORE-CHAIN");
INSERT INTO `Place` (`id`, `description`) VALUES (256,"VIDEO STORE-INDEPENDENT");
INSERT INTO `Place` (`id`, `description`) VALUES (260,"MOTEL/HOTEL");
INSERT INTO `Place` (`id`, `description`) VALUES (261,"MUSIC THEATRE");
INSERT INTO `Place` (`id`, `description`) VALUES (263,"MOTORCYCLE SHOP");
INSERT INTO `Place` (`id`, `description`) VALUES (264,"PARK-FEDERAL");
INSERT INTO `Place` (`id`, `description`) VALUES (265,"PAWN SHOP");
INSERT INTO `Place` (`id`, `description`) VALUES (266,"OIL FIELD");
INSERT INTO `Place` (`id`, `description`) VALUES (267,"MOVIE HOUSES/THEATER");
INSERT INTO `Place` (`id`, `description`) VALUES (268,"NURSING HOME");
INSERT INTO `Place` (`id`, `description`) VALUES (269,"PARK");
INSERT INTO `Place` (`id`, `description`) VALUES (270,"FORREST PRESERVE");
INSERT INTO `Place` (`id`, `description`) VALUES (271,"WILDLIFE MANAGEMENT AREA");
INSERT INTO `Place` (`id`, `description`) VALUES (272,"CAMPING GROUNDS");
INSERT INTO `Place` (`id`, `description`) VALUES (273,"LAKE OR WATERWAY");
INSERT INTO `Place` (`id`, `description`) VALUES (274,"PARK BUILDING");
INSERT INTO `Place` (`id`, `description`) VALUES (275,"PARK-PICNIC/REC. AREA");
INSERT INTO `Place` (`id`, `description`) VALUES (276,"PARK ROAD OR SCENIC DRIVE");
INSERT INTO `Place` (`id`, `description`) VALUES (277,"PARKING LOT - GENERAL USE");
INSERT INTO `Place` (`id`, `description`) VALUES (278,"PARKING LOT - BUSINESS");
INSERT INTO `Place` (`id`, `description`) VALUES (279,"PARKING LOT - MUNICIPAL");
INSERT INTO `Place` (`id`, `description`) VALUES (280,"NEW OR USED CAR LOTS");
INSERT INTO `Place` (`id`, `description`) VALUES (281,"PHARMACY - INDEPENDENT");
INSERT INTO `Place` (`id`, `description`) VALUES (282,"PHARMACY - CHAIN");
INSERT INTO `Place` (`id`, `description`) VALUES (283,"BUILDING-PUBLIC");
INSERT INTO `Place` (`id`, `description`) VALUES (284,"BUILDING-FEDERAL");
INSERT INTO `Place` (`id`, `description`) VALUES (285,"BUILDING-STATE");
INSERT INTO `Place` (`id`, `description`) VALUES (286,"BUILDING LOCAL GOVERNMENT");
INSERT INTO `Place` (`id`, `description`) VALUES (287,"PUBLIC FACILITIES (WATER");
INSERT INTO `Place` (`id`, `description`) VALUES (288,"JAIL-PENAL INSTITUTION");
INSERT INTO `Place` (`id`, `description`) VALUES (289,"RESIDENCE-PORCH");
INSERT INTO `Place` (`id`, `description`) VALUES (290,"RESIDENCE-PRIVATE");
INSERT INTO `Place` (`id`, `description`) VALUES (291,"RESIDENCE-YARD");
INSERT INTO `Place` (`id`, `description`) VALUES (293,"RESTAURANT-INDEPENDENT");
INSERT INTO `Place` (`id`, `description`) VALUES (294,"RESTAURANT-CHAIN");
INSERT INTO `Place` (`id`, `description`) VALUES (295,"RIVER BANK");
INSERT INTO `Place` (`id`, `description`) VALUES (296,"RETIREMENT HOME (EX 268)");
INSERT INTO `Place` (`id`, `description`) VALUES (297,"ROLLER SKATING/ICE RINK");
INSERT INTO `Place` (`id`, `description`) VALUES (298,"SAVINGS AND LOAN");
INSERT INTO `Place` (`id`, `description`) VALUES (299,"SCHOOL GROUNDS");
INSERT INTO `Place` (`id`, `description`) VALUES (300,"SCHOOL");
INSERT INTO `Place` (`id`, `description`) VALUES (301,"SPORTING GDS ST-INDEDEPND");
INSERT INTO `Place` (`id`, `description`) VALUES (302,"SPORTING GDS STORE-CHAIN");
INSERT INTO `Place` (`id`, `description`) VALUES (303,"SIDEWALK");
INSERT INTO `Place` (`id`, `description`) VALUES (304,"STREET");
INSERT INTO `Place` (`id`, `description`) VALUES (305,"SPORTS ARENA OR STADIUM");
INSERT INTO `Place` (`id`, `description`) VALUES (306,"STORAGE SHED");
INSERT INTO `Place` (`id`, `description`) VALUES (307,"SWIMMING POOL");
INSERT INTO `Place` (`id`, `description`) VALUES (308,"SHOPPING MALL");
INSERT INTO `Place` (`id`, `description`) VALUES (309,"TAXI");
INSERT INTO `Place` (`id`, `description`) VALUES (310,"ROADS-TOLL");
INSERT INTO `Place` (`id`, `description`) VALUES (311,"ROADS-OTHER");
INSERT INTO `Place` (`id`, `description`) VALUES (312,"TRAILER(TRUCK OR TRACTOR)");
INSERT INTO `Place` (`id`, `description`) VALUES (315,"VEHICLE");
INSERT INTO `Place` (`id`, `description`) VALUES (317,"RAILROAD-TRAIN YARD");
INSERT INTO `Place` (`id`, `description`) VALUES (319,"RAILROAD-RIGHT OF WAY");
INSERT INTO `Place` (`id`, `description`) VALUES (320,"RAILROAD-TRAIN");
INSERT INTO `Place` (`id`, `description`) VALUES (322,"TRAIN - COMMUTER (EX 321)");
INSERT INTO `Place` (`id`, `description`) VALUES (323,"TRAIN DEPOT - CTA");
INSERT INTO `Place` (`id`, `description`) VALUES (325,"TRUCK STOP");
INSERT INTO `Place` (`id`, `description`) VALUES (326,"TRUCK TERMINAL");
INSERT INTO `Place` (`id`, `description`) VALUES (327,"WAREHOUSE");
INSERT INTO `Place` (`id`, `description`) VALUES (328,"WAREHOUSE SHIPPING DOCK");
INSERT INTO `Place` (`id`, `description`) VALUES (329,"WOODED AREA");
INSERT INTO `Place` (`id`, `description`) VALUES (330,"OTHER PLACE THAN LISTED");
INSERT INTO `Place` (`id`, `description`) VALUES (331,"UNKNOWN");
INSERT INTO `Place` (`id`, `description`) VALUES (332,"RENTAL STORAGE FACILITY");
INSERT INTO `Place` (`id`, `description`) VALUES (333,"STATE REST AREA");
INSERT INTO `Place` (`id`, `description`) VALUES (334,"PARKING-UNDERGROUND");
INSERT INTO `Place` (`id`, `description`) VALUES (400,"PERMIT PARKING ON STREET");
