INSERT INTO `CrimeType` (`id`, `description`) VALUES (110,"MURDER-FIRST DEGREE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (130,"MURDER-SECOND DEGREE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (141,"MANSLAUGHTER-INV/RECK HOM. NON-VEH");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (142,"MANSLAUGHTER-INV/RECK HOM. VEHICLE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (150,"HOMICIDE-JUSTIFIABLE HOMICIDE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (165,"MANSLAUGHTER-INVOLUNT. UNBORN CHILD");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (170,"HOMICIDE-DRUG INDUCED");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (190,"SOLICITION FOR MURDER");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (260,"SEXUAL-ASSAULT-CRIMINAL");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (261,"SEXUAL ASSAULT-AGG CRIMINAL");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (262,"SODOMY-FORCIBLE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (280,"PREDATORY CRIM SEX ASSAULT OF CHILD");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (281,"SEXUAL ASSAULT-W/OBJECT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (310,"ROBBERY-ARMED");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (320,"ROBBERY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (325,"VEHICULAR HIJACKING");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (326,"VEHICULAR HIJACKING-AGGRAVATED");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (330,"ROBBERY-AGGRAVATED");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (410,"BATTERY-AGGRAVATED");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (460,"BATTERY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (470,"RECKLESS CONDUCT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (475,"BATTERY-UNBORN CHILD");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (480,"BATTERY-HEINOUS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (485,"BATTERY-AGG-CHILD");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (486,"BATTERY-DOMESTIC");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (487,"BATTERY-AGG-UNBORN CHILD");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (488,"BATTERY-AGG DOMESTIC");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (490,"RITUAL MUTILATION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (491,"STALKING-AGGRAVATED");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (495,"BATTERY-AGG-SENIOR CITIZEN");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (510,"ASSAULT-AGGRAVATED");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (560,"ASSAULT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (610,"BURGLARY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (625,"BURGLARY RESIDENTIAL");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (650,"HOME INVASION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (710,"THEFT FROM MOTOR VEHICLE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (720,"THEFT OF MOTOR VEH PARTS & ACCESS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (730,"BURGLARY MOTOR VEH PARTS & ACCESS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (760,"BURGLARY FROM MOTOR VEHICLE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (770,"VEHICULAR INVASION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (805,"THEFT OF LOST/MISLAID PROPERTY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (810,"THEFT OVER");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (815,"THEFT OVER $500");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (820,"THEFT UNDER");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (825,"THEFT $500 AND UNDER");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (860,"THEFT-RETAIL");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (865,"THEFT-DELIVERY CONTAINER");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (870,"POCKET-PICKING");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (880,"PURSE SNATCHING");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (890,"THEFT FROM BUILDING");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (895,"THEFT FROM COIN-OP MACHINE/DEVICE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (910,"THEFT-MOTOR VEHICLE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1010,"ARSON");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1025,"ARSON-AGGRAVATED");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1030,"EXPLOSIVES/INCENDIARY DEVICE-POSS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1050,"HUMAN TRAFFICKING-COMM SEX ACTS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1110,"DECEPTIVE PRACTICES");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1120,"FORGERY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1125,"FALSE ID-POSS (MISC)");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1130,"FRAUD-DECEPTION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1131,"HOME REPAIR FRAUD");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1135,"FRAUD-INSURANCE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1137,"THEFT-IDENTITY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1138,"THEFT-AGG IDENTITY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1140,"EMBEZZLEMENT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1150,"FRAUD-CREDIT CARD");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1170,"IMPERSONATING AN OFFICER");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1180,"FALSE PERSONATION OF PEACE OFFICER");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1195,"FINANCIAL EXPLOIT. ELDERLY/DISABLED");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1200,"POSSESSION STOLEN PROPERTY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1210,"THEFT-LABOR OR SERVICES");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1220,"THEFT-LOST/MISLAID PROPERTY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1230,"POSSESSION OF KEY-COIN OPER. DEVICE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1235,"UNLAWFUL USE OF RECORDED SOUNDS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1240,"COMPUTER TAMPERING");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1241,"COMPUTER TAMPERING-AGGRAVATED");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1242,"COMPUTER FRAUD");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1245,"THEFT-CABLE TV");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1255,"UNIDENTIFIABLE SOUND/AUDIO VISUAL R");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1260,"THEFT-LIBRARY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1261,"UNAUTHORIZED VIDEOTAPING/LIVE VIDEO");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1305,"CRIMINAL DEFACEMENT OF PROPERTY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1310,"CRIMINAL DAMAGE TO PROPERTY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1330,"TRESPASS TO LAND/REAL PROPERTY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1340,"CRIMINAL DAMAGE GOVT SUPPORT PROP");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1350,"TRESPASS-STATE SUPPORTED LAND");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1360,"TRESPASS-VEHICLE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1365,"TRESPASS-RESIDENCE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1370,"CRIMINAL DAMAGE-FIREFIGHTING APPART");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1375,"VANDALISM-INSTITUTIONAL");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1380,"UNLAWFUL STORAGE OF WEAPONS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1410,"UNLAWFUL USE OF WEAPONS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1411,"AGGR UNLAWFUL USE OF WEAPON");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1415,"AGG DISCHARGE OF FIREARM");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1420,"UNLAWFUL SALE/PURCHASE OF FIREARMS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1425,"UNLAWFUL POSS FIREARM & AMMUNITION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1430,"UNLAWFUL POSS/USE WEAPON BY FELON");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1431,"ARMED HABITUAL CRIMINAL");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1435,"UNLAWFUL SALE/DEL FIREARM AT SCHOOL");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1438,"POSSESSION OF STOLEN FIREARM");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1450,"DEFACING IDENTI.MARKS OF FIREARMS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1460,"NO FOID CARD");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1476,"UNLAWFUL DISCH FIREARM PROJECTILES");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1477,"RECKLESS DISCHARGE OF A FIREARM");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1504,"SOLICITATION OF A SEXUAL ACT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1505,"PROSTITUTION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1510,"PROSTITUTE - SOLICITING FOR");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1515,"PANDERING-PROMOTE PROSTITUTION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1520,"PROSTITUTION-KEEP A PLACE OF");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1521,"PROSTITUTION-KEEPING PLACE OF JUVEN");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1525,"PROSTITUTE-PATRONIZING");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1530,"PIMPING-PROMOTING PROSTITUTION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1531,"PIMPING-JUVENILE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1535,"OBSCENITY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1540,"SEX OFFENSES-HARMFUL MATERIAL DIST");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1544,"SEXUAL EXPLOITATION OF A CHILD");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1545,"EXPLOITATION OF A CHILD");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1562,"SEXUAL ABUSE-AGGRAVATED");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1563,"SEXUAL ABUSE-CRIMINAL");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1564,"CRIMINAL TRANSMISSION OF HIV");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1565,"INDECENT SOLICITATION OF CHILD");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1566,"INDECENT SOLICITATION OF AN ADULT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1570,"PUBLIC INDECENCY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1572,"ADULTERY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1576,"BIGAMY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1580,"SEX RELATIONS WITHIN FAMILIES");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1581,"NON-CONSENSUAL DISS SEX IMAGES");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1582,"PORNOGRAPHY-CHILD");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1583,"REVENGE PORNOGRAPHY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1585,"SEX OFFENSES-ALL OTHERS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1615,"GAMBLING-BETTING OR WAGERING");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1650,"GAMBLING-OPERATING CARD GAME");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1651,"GAMBLING-PLAYING CARD GAME");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1660,"GAMBLING-OPERATING DICE GAME");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1661,"GAMBLING-PLAYING DICE GAME");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1670,"GAMBLING DEVICE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1680,"SPORTS TAMPERING");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1710,"ENDANG LIFE/HEALTH OF CHILD");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1715,"SALE OF TOBACCO PRODUCTS TO MINORS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1720,"NEGLECT & DEPENDENCY OF CHILDREN");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1725,"CONTRIBUTING CRIM DELINQUENCY JUV");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1726,"INDECENT VISUAL DEPICT - MINOR");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1730,"CURFEW");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1740,"RUNAWAY - MINOR REQUIRE AUTH INTER");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1750,"CHILD ABUSE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1755,"CHILD ABANDONMENT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1770,"TRUANCY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1810,"CANNABIS POSS OVER 10 - 100 G -MISD");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1811,"CANNABIS POSS 30 G AND UNDER - OLD");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1812,"CANNABIS POSS OVER 30 G - OLD");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1813,"CANNABIS POSS OVER 100 G -FEL");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1814,"CANNABIS POSS 10 GM OR LESS -ORD");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1815,"CANNABIS TRAFFICKING");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1817,"UNLAWFUL CANNABIS MANUFACTURING");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1821,"DEL/MANUF CANNABIS UNDER 30 G -MISD");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1822,"DEL/MANUF CANNABIS OVER 30 G -FEL");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1823,"DEL/MANUF CANNABIS 10 G - 30 G -FEL");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1830,"CANNABIS CONTROL-CASUAL DELIVERY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1840,"CANNABIS-DELIVERY PERSONS <18");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1850,"CANNABIS PLANT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1860,"CANNABIS-CALCULATED CONSPIRACY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1900,"INTOXICATING COMPOUNDS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1910,"METHAMPHETAMINE-POSSESSION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1915,"METH PRECURSORS-POSSESSION/DELIVERY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1930,"METHAMPHETAMINE - MANUFACTURING");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1935,"DEL/POSS W/INTENT DELIVER METH");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (1940,"METH/PRECURSOR/ANHYDROUS TRAFFICKIN");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2010,"CONTROLLED SUBSTANCE-MANUF-INTENT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2011,"MANUFACTURE CONTROLLED SUB");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2012,"DELIVERY CONTROLLED SUB");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2013,"POSSESSION W/INTENT TO DELIVER");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2020,"CONTROLLED SUBSTANCE-POSSESSION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2030,"CONTROLLED SUBSTANCE-LOOK-ALIKE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2040,"CONTROLLED SUBSTANCE-POSS W/INTENT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2050,"CRIMINAL DRUG CONSPIRACY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2061,"POSSESSION PRESCRIPTION FORM");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2065,"UNLAWFUL USE OF A  BUILDING");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2070,"CONTROLLED SUBSTANCE-DELIV-PERS <18");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2110,"HYPODERMIC NEEDLE/SYRINGE-POSS/SALE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2160,"DRUG PARAPHERNALIA-SALE/DELIVERY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2170,"DRUG EQUIPMENT-POSSESSION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2171,"POSS OF DRUG PARAPHERNALIA -ORD");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2210,"LIQUOR-SALE TO MINORS/DRUNKARDS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2220,"LIQUOR-ILLEGAL POSS. BY MINOR");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2230,"LIQUOR-ILLEGAL CONSUMPTION BY MINOR");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2240,"MISREPRES. OF AGE BY MINOR");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2250,"LIQUOR-ILLEGAL ACCESS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2310,"USE/SALE/DEL OF INTOXICATING COMPOU");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2410,"DRIVING UNDER THE INFL-ALCOHOL");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2415,"BREATH ALCOHOL OVER LIMIT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2420,"DRIVING UNDER INFLUENCE-DRUGS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2430,"ILLEGAL TRANSPORTATION OF LIQUOR");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2440,"RECKLESS DRIVING");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2445,"HIT AND RUN");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2446,"LEAVING SCENE INJURY ACCIDENT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2447,"LEAVING SCENE PROPERTY DAMAGE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2450,"STREET RACING");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2455,"NO REGISTRATION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2460,"CANCEL/SUSPEND/REVOKED REGISTRATION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2461,"OPERATE UNINSURED MOTOR VEHICLE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2462,"OPERATE MV W/SUSPEND REGISTRATION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2463,"FALSE AUTO INSURANCE CARD");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2465,"IMPROPER USE OF REGISTRATION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2470,"NO DRIVERS LICENSE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2475,"MOTOR VEH ANTI-THEFT LAWS (MISDEMEA");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2480,"SUSPEND REVOKED DRIVERS LICENSE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2481,"DRIVING UNDER SUSPENDED LICENSE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2482,"DRIVING UNDER REVOKED LICENSE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2485,"SEAT BELT-DRIVER & PASSENGER");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2490,"UNLAWFUL USE OF DRIVERS LICENSE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2495,"FLEEING OR ATTEMPT TO ELUDE POLICE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2496,"AGG FLEE/ATTEMPT ELUDE OFFICER");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2805,"VAGRANCY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2807,"DRUNKENNESS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2810,"PROWLER");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2820,"TELEPHONE THREAT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2825,"HARASSMENT BY TELEPHONE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2826,"HARASSMENT BY ELECTRONIC COMMUNICAT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2830,"OBSCENE PHONE CALLS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2835,"EAVESDROPPING");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2840,"FALSE FIRE ALARM");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2850,"BOMB THREAT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2860,"FALSE POLICE REPORT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2870,"PEEPING TOM");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2880,"CONFINEMENT TO PREVENT CRIME");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2890,"DISORDERLY CONDUCT-ALL OTHER");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2895,"INTER W/EMERGENCY EQUIP/COMMUNICATI");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (2900,"AIR RIFLES");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (3000,"FIREWORKS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (3100,"MOB ACTION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (3200,"ARMED VIOLENCE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (3300,"PUBLIC DEMONSTRATION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (3400,"LOOTING");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (3500,"PROPERTY FORFEITURE-MAINTAIN PUBLIC");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (3710,"RESIST/OBSTRUCT/DISARM AN OFFICER");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (3711,"RESIST/OBS CORRECT/POLICE/FIRE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (3720,"REFUSING TO AID AN OFFICER");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (3730,"OBSTRUCTING JUSTICE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (3731,"OBSTRUCTING IDENTIFICATION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (3735,"OBSTRUCTING IDENTIFICATION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (3740,"CONCEALING OR AIDING A FUGITIVE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (3750,"ESCAPE-FAILURE TO REPORT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (3760,"ESCAPE-AIDING");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (3770,"BRINGING CONTRABAND INTO PENAL INST");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (3800,"INTERFER W/JUDICIAL PROCED.");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (3810,"CONTEMPT OF COURT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (3820,"PERJURY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (3910,"BRIBERY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (3920,"OFFICIAL MISCONDUCT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (3960,"INTIMIDATION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (3961,"INTIMIDATION-AGGRAVATED");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (3965,"HATE CRIME");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (3967,"STALKING");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (3968,"CYBERSTALKING");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (3975,"COMPELLING ORGANIZATION MEMBERSHIP");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (4210,"KIDNAPPING");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (4220,"KIDNAPPING-AGGRAVATED");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (4225,"UNLAWFUL RESTRAINT-AGGRAVATED");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (4230,"UNLAWFUL RESTRAINT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (4250,"CHILD ABDUCTION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (4255,"UNLAWFUL VISITATION INTERFERENCE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (4260,"CHILD ABDUCTION-AIDING AND ABETTING");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (4270,"HARBOURING A RUNAWAY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (4310,"BURGLARY TOOLS-POSSESSION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (4320,"TERRORISM - MAKE THREATS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (4387,"VIOLATION ORDER PROTECTION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (4388,"VIOLATION CIVIL NO CONTACT ORD");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (4389,"VIOLATION STALKING NO CONTACT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (4505,"SEX OFFENDER-FAIL TO REGISTER");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (4510,"PROBATION VIOLATION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (4515,"SEX OFFENDER-FAIL CHANGE ADD/EMPLOY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (4520,"SEX OFFENDER- CHILD CONTACT/RESIDE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (4525,"SEX OFFENDER - PROHIBITED ZONE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (4530,"SEX OFFENDER-OTHER VIOLATION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (4570,"VIOL CHILD MURDERER/VIOLENT OFF ACT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (4600,"VIOLATION OF BAIL BOND");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (4625,"PAROLE VIOLATION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (4652,"WILLFULLY PROVIDE FALSE INF/SEX OFF");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (4710,"SUSPICION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (4729,"UNLAWFUL POSS RES ALIEN ID CARD");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (4730,"ILLEGAL ENTRY-ALIEN");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (4750,"DOMESTIC-DISCL DOM VIO VICTIM LOCAT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (4751,"INTERFER W/REPORT DOM VIOLENCE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (4775,"ENDANGERMENT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (4800,"MONEY LAUNDERING");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (4870,"DOMESTIC DISPUTE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (4900,"TELEPHONE INTERFERENCE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (4950,"DOMESTIC-INTERFERENCE WITH REPORT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (5000,"OTHER CRIMINAL OFFENSES");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (5081,"WARRANT-IN STATE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (5082,"WARRANT-OUT OF STATE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (5083,"RECOVERED PROPERTY ONLY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (5084,"RECOVERED STOLEN VEHICLE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (5100,"ILLEGAL DUMPING");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6519,"ABANDONED JUNK VEHICLES");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6520,"BICYCLE WARNING TICKET");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6529,"OTHER TRAFFIC RELATED SERVICES");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6561,"ACCIDENT INVOLVING DEATH");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6562,"ACCIDENT INVOLVING INJURY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6563,"ACCIDENT INVOLVING NON-INJURY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6564,"ACCIDENT W/NON-VEH PROP DAMAGE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6565,"ACCIDENT INVOLVING TRAIN");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6566,"ACCIDENT INVOLVING POLICE VEHICLE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6567,"ACCIDENT INVOLVING OTHER CITY VEH");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6568,"ACCIDENT INVOLVING OTHER CITY PROP");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6569,"ACCIDENT ON PRIVATE PROPERTY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6572,"ACCIDENT INVOLVING PEDESTRIAN");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6573,"ACCIDENT INVOLVING MOTORCYCLE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6576,"ACCIDENT INVOLVING BICYLE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6578,"ACCIDENT HIT AND RUN");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6579,"ACCIDENT OTHER");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6582,"PARKING VIOLATIONS-ILLEGAL PARKING");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6583,"PARKING-2 AM TO 6 AM");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6589,"PARKING VIOLATIONS-ALL OTHER");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6590,"PARKING-HANDICAP");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6601,"SPEEDING (RADAR)");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6602,"SPEEDING (PACED)");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6603,"SPEEDING (SCHOOL ZONE)");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6604,"SPEEDING (TOO FAST FOR CONDITIONS)");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6605,"TRAFFIC SIGN VIOLATION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6606,"TRAFFIC SIGNAL VIOLATION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6607,"IMPROPER PASSING");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6608,"IMPROPER LANE USAGE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6609,"FOLLOWING TOO CLOSELY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6610,"IMPROPER TURN-NOT AT INTERSECTION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6611,"IMPROPER TURN AT INTERSECTION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6612,"IMPROPER RIGHT TURN ON RED");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6613,"IMPROPER U-TURN");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6614,"FAILURE TO SIGNAL");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6615,"UNSAFE MOVEMENT ON ROADWAY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6616,"FAILURE TO YIELD AT INTERSECTION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6617,"FAILURE TO YIELD TURNING LEFT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6618,"FAILURE TO YIELD PRIVATE ROAD");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6619,"FAILURE TO YIELD PEDESTRIAN");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6620,"FAILURE TO YIELD FROM STOP SIGN");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6621,"FAILURE TO REDUCE SPEED");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6622,"LEAVING THE SCENE OF AN ACCIDENT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6623,"CHILD RESTRAINT VIOLATIONS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6624,"WEARING HEADSETS WHILE DRIVING");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6625,"LOUD STEREO IN VEHICLE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6626,"NO CERTIFICATE OF TITLE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6627,"NO VALID DL CLASSIFICATION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6628,"IMPROPER BACKING");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6629,"PASSING STOPPED SCHOOL BUS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6630,"DRIVING WITHOUT LIGHTS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6631,"NO TAILLIGHTS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6632,"FAILURE TO DIM HEADLIGHTS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6633,"IMPROPER LIGHTING/ONE HEADLIGHT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6634,"MUFFLER VIOLATION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6635,"NO PHONE IN SCHOOL/WORK ZONES");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6636,"SIZE,WEIGHT,LOAD VIOLATIONS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6637,"MOTORCYCLE VIOLATIONS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6638,"ELECTRONIC COMMUNICATION-TEXTING");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6639,"GRADUATED DRIVER");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6640,"ELECTRONIC COMMUNICATION-VOICE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6641,"DEPOSITING MATERIAL ON HIGHWAY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6648,"OTHER EQUIPMENT VIOLATIONS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6649,"OTHER MOVING VIOLATIONS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6653,"UI WARNING SIGNAL");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6670,"OTHER TRAFFIC TICKETS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6671,"IMPROPER LANE USAGE-ONE-WAY ST");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6672,"OBSTRUCTED REG/IMPROP DISPLAY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6673,"EXPIRED REGISTRATION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6674,"PEDESTRIAN WALKING ON ROADWAY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6675,"PEDESTRIAN UNDER THE INFLUENCE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6676,"DISOBEY TRAFFIC SIGNAL/RR CROSSING");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6677,"IMPROPER PARKING ON ROADWAY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6678,"NO PARKING/HANDICAP ZONE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6679,"PARKING WHERE PROHIBITED");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6680,"NO LIGHT ON BICYCLE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6681,"DISOBEY POLICE OFFICER");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6682,"AVOIDED TRAFFIC CONTROL");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6683,"ILLEGAL SQUEALING/SCREECHING TIRES");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6684,"SPEEDING-CONSTRUCTION ZONE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6685,"IMPROPER STARTING OF PARKED VEHICLE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6686,"IMPROPER USE OF SIGNAL");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6687,"FAILURE TO YIELD TO EMERGENCY VEH");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6688,"UNSAFE EQUIPMENT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6689,"NO HEADLIGHT(MOTORCYCLE)");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6690,"NO REAR REGISTRATION LIGHT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6691,"NO BRAKE LIGHTS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6692,"ILLEGAL LIGHTS/RED OR FLASHING");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6693,"ILLEGAL USE OF BLUE LIGHTS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6694,"OBSTRUCTED/TINTED WINDSHIELD");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6695,"NO FRONT PLATE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6696,"UNLAWFUL POSS OF REG(FORGED,ALTERED");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6697,"UNLAWFUL USE REG(WRONG VEH)");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6698,"D/L NOT ON PERSON");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6699,"FAIL TO NOTIFY SOS/CHANGE OF ADDRES");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6700,"CANINE SWEEP - IDOT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6701,"OTHER TRAFFIC RELATED INCIDENTS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6702,"TERRY STOPS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6703,"PEDESTRIAN FAILED TO YIELD");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6709,"PEDESTRIAN SOLICITING ON ROADWAY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6710,"PEDESTRIAN DISOBEYING SIGNAL");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6711,"PED CROSS AT OTHER THAN CROSSWALK");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (6712,"OTHER PEDESTRIAN VIOLATIONS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (7710,"PROTECTIVE CUSTODY - JUVENILE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (7716,"MINOR REQUIRING AUTHORITATIVE INTER");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (7738,"GANG ACTIVITY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8101,"LIQUOR-HOURS OF OPERATION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8102,"LIQUOR-SALE TO MINORS,DRUNKS,ETC");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8103,"LIQUOR-TRANSPORTING IN MV");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8104,"LIQUOR-CLASS A/MINOR RESTRICT.");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8105,"LIQUOR- WARNING TO MINORS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8106,"LIQUOR-FURNISH FALSE ID TO MINORS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8107,"LIQUOR-ID OFFENSES");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8108,"LIQUOR-PURCH/POSS/CONSUMP BY MINORS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8109,"LIQUOR-LICENSE REQUIRED TO SELL");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8110,"LIQUOR-OPEN CONTAINER/PUBLIC PROP.");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8111,"LIQUOR-OPEN CONT. OUT OF PREMISES");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8152,"CRUELTY TO ANIMALS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8161,"ANIMAL - MISC CALLS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8212,"FOOD SERVICE LICENSE REQUIRED");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8215,"RAFFLE LICENSE REQUIRED");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8266,"MIP UNDER");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8332,"DISORDERLY CONDUCT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8364,"TRESPASS TO GOV'T LAND");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8464,"PARKING ENFORCEMENT BOOT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8477,"DISPLAY LICENSE PLATE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8480,"NUMBER OF PASSENGERS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8508,"LIBRARY-FAIL TO RETURN BOOK");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8601,"HINDERING/REFUSING TO OBEY CITY OFC");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8603,"ASSAULT-CITY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8604,"BATTERY-CITY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8605,"RECKLESS CONDUCT-CITY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8606,"BREAKING & ENTERING-CITY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8607,"THEFT-CITY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8608,"CRIMINAL DAMAGE-CITY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8610,"TRESPASS TO LAND-CITY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8611,"TRESPASS TO CITY LAND-CITY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8612,"THEFT-RETAIL-CITY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8613,"LOITERING-CITY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8614,"DISORDERLY CONDUCT-CITY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8615,"MOB ACTION-CITY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8616,"FIREWORKS-CITY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8617,"CURFEW FOR MINORS-CITY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8618,"PUBLIC URINATION-CITY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8619,"THROWING STONES/MISSILES/ETC");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8620,"SLINGS/AIR GUNS PROHIBITED");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8621,"POSS OF CANNABIS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8622,"POSS DRUG PARAPHERNALIA");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8623,"ALLOWING A NUISANCE PARTY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8625,"AGGRESSIVE SOLICITATION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8701,"NOISE PROHIBITION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8703,"MOTOR VEH/NOISE OFFENSES");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8704,"MISUSE OF HORNS & SIGNAL DEVICES");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8707,"ONLY LIC. PEDDLERS ON STREET");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8708,"SOLICITOR LICENSE REQUIRED");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8710,"NO OBSTRUCT STREET/SIDEWALK");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8806,"TAXI BUSINESS LICENSE REQ.");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8807,"TAXI DRIVER'S LIC. REQUIRED");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8808,"TAXI STATE LICENSE REQUIRED");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8809,"USE OF SKATES, COASTERS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8812,"UNLAWFUL RIDING");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8813,"RIDING ON SIDEWALKS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8814,"TAMPERING W/METERS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8816,"PARKING TICKETS-UNPAID");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8817,"MOBILE DEVICE ACCIDENT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8818,"BICYCLIST -TRAFFIC CODE APPLIES");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8819,"BICYCLIST -OBEY TRAFFIC CONTROL DEV");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8898,"OTHER/MISC CITY ORDINANCE VIOLATION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8901,"VEHICLES AFTER SUNDOWN - PK DIST");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8904,"KEEPING TO DRIVE - PK DIST");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8906,"ASSEMBLY W/OUT PERMIT - PK DIST");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8907,"DEFACING PROPERTY - PK DIST");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8908,"FIREARMS PROHIBITED-PK DIST");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8911,"LIQUOR PROHIBITED - PK DIST");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8912,"LITTERING PROHIBITED - PK DIST");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8914,"FIRES PROHIBITED-PK DIST");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8918,"PARKS CLOSED 10PM-6AM-PK DIST");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8919,"DISOBEY TRFC CONTROL DEV - PK DIST");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8925,"TRESPASS - PK DIST");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8926,"DOG PARK VIOLATIONS - PK DIST");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8930,"ALL OTHER PARK DIST VIOLATIONS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (8998,"OTHER/MISC UPD ORDIANCE -PRIOR 2008");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9001,"ASSIST FIRE DEPT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9002,"ASSIST COUNTY POLICE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9003,"ASSIST STATE POLICE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9004,"ASSIST OTHER POLICE DEPT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9005,"ASSIST OTHER GOVT AGENCY/EOD");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9006,"METRO ACTIVATION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9012,"ASSIST SCHOOLS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9019,"ASSIST AGENCY (OTHER)");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9024,"CANINE SEARCH  TRACK");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9025,"CANINE SEARCH  VEHICLE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9039,"PUBLIC SERVICE - OTHER");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9044,"EXPLOSION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9045,"EXPLOSIVE DEVICE-INVESTIGATION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9056,"SOLICITOR COMPLAINTS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9058,"LOUD NOISE PROHIBITION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9059,"OTHER PUBLIC COMPLAINTS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9061,"LOST ARTICLES");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9062,"FOUND ARTICLES");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9063,"LOST DRIVERS LICENSE/PLATE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9064,"MISSING PERSON ADULT/MALE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9065,"MISSING PERSON ADULT/FEMALE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9066,"MISSING PERSON JUVENILE/MALE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9067,"MISSING PERSON JUVENILE/FEMALE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9068,"ABANDONED BICYCLE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9071,"JUVENILE OTHER");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9075,"WARRANTS-NONCRIMINAL/SUMMONS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9077,"LICENSES AND PERMITS ISSUED");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9078,"LICENSES AND PERMITS DENIED");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9079,"TAXI PROVISIONAL LICENSE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9081,"ASSIST TOW TRUCK");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9101,"SUSPICIOUS AUTO");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9102,"SUSPICIOUS NOISE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9103,"SUSPICIOUS PERSON");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9105,"NEIGHBORHOOD TROUBLE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9106,"OTHER TROUBLE/INFO RPT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9109,"ACCIDENT NON-TRAFFIC OTHER");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9119,"OTHER INVESTIGATION QUASI-CRIMINAL");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9201,"DOG BITE  HOME");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9202,"DOG BITE  OCCUPATIONAL");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9203,"DOG BITE  PUBLIC");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9204,"BITE-DOG");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9205,"OTHER ANIMAL BITES  HOME");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9207,"OTHER ANIMAL BITES  PUBLIC");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9208,"BITE-OTHER ANIMALS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9209,"RUNNING AT LARGE-STRAY DOG");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9210,"ANIMALS-STRAY OTHER");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9211,"DOGS DISTURBING THE PEACE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9212,"ANIMAL-SICK/INJURED");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9213,"ANIMAL-DEAD");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9214,"ANIMAL-LOST");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9215,"ANIMAL-FOUND");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9219,"ANIMAL COMPLAINTS-OTHER");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9220,"ANIMAL CRUELTY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9231,"DOG AT LARGE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9234,"NO RABIES TAG - DOG");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9235,"NO RABIES TAG - CAT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9240,"ANIMALS-CRUELTY");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9241,"INTERFERING W/ POLICE DOGS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9243,"ANIMALS DISTURBING THE PEACE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9245,"KEEPING OF VICIOUS DOG PROHIBITED");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9431,"DEAD BODY-NATURAL CAUSES");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9432,"DEAD BODY-SUSPICIOUS CIRCUMSTANCES");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9433,"DEAD BODY-ACCIDENTAL/NON-TRAFFIC");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9435,"DEATH INVESTIGATION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9436,"HEROIN OVERDOSE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9439,"DEAD BODY-OTHER SUDDEN DEATH");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9711,"CRISIS INTERVEN. - SUICIDE IDEATION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9712,"CRISIS INTERVEN. - SUICIDE ATTEMPT");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9713,"CRISIS INTERVEN. - SUICIDE COMPLETE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9901,"IMPROPER DEPOSIT OF GARBAGE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9902,"DISPOSAL OF GARBAGE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9905,"SCATTERING REFUSE PROHIBITED");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9906,"OPEN BURNING");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9907,"MUNICIPAL WASTE CONTAINER VIOL");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9908,"ABANDON MOTOR VEHICLE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9911,"FUGITIVE FROM JUSTICE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9918,"FIGHTS/RIOTS/BRAWLS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9922,"SEARCH WARRANT SERVICE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9925,"ZERO TOLERANCE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9940,"UNAUTH. COLLECTION RECYCLED MATER.");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9941,"UNL. REMOVAL RECYCLED MATERIALS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9943,"PLACING GRASS/LEAVES/ETC IN STREET");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9944,"GARBAGE CONTAINERS REQUIRED");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9947,"GARBAGE TRUCK REQUIREMENTS");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9948,"ANIMAL-WASTE");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9991,"MURDER/VIOLENT OFFENDER REGISTRATIO");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9995,"SEX OFFENDER-ADDRESS VERIFICATION");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9997,"OFFICER INVOLVED SHOOTING");
INSERT INTO `CrimeType` (`id`, `description`) VALUES (9998,"SEX OFFENDER-REGISTERED FILE");
